import { registerTool } from './registry';
import { definition as readFileDef, handler as readFileHandler } from './definitions/readFile';
import { definition as writeFileDef, handler as writeFileHandler } from './definitions/writeFile';
import { definition as editFileDef, handler as editFileHandler } from './definitions/editFile';
import { definition as createFileDef, handler as createFileHandler } from './definitions/createFile';
import { definition as renameFileDef, handler as renameFileHandler } from './definitions/renameFile';
import { definition as listDirectoryDef, handler as listDirectoryHandler } from './definitions/listDirectory';
import { definition as searchFilesDef, handler as searchFilesHandler } from './definitions/searchFiles';
import { definition as runCommandDef, handler as runCommandHandler } from './definitions/runCommand';
import { definition as gitStatusDef, handler as gitStatusHandler } from './definitions/gitStatus';
import { definition as gitAddDef, handler as gitAddHandler } from './definitions/gitAdd';
import { definition as gitCommitDef, handler as gitCommitHandler } from './definitions/gitCommit';
import { definition as gitDiffDef, handler as gitDiffHandler } from './definitions/gitDiff';
import { definition as webSearchDef, handler as webSearchHandler } from './definitions/webSearch';
import { definition as readUrlDef, handler as readUrlHandler } from './definitions/readUrl';
import { definition as askUserDef, handler as askUserHandler } from './definitions/askUser';
import { definition as codeAnalysisDef, handler as codeAnalysisHandler } from './definitions/codeAnalysis';
import { definition as invokeSubagentDef, handler as invokeSubagentHandler } from './definitions/invokeSubagent';
import { definition as sendMessageDef, handler as sendMessageHandler } from './definitions/sendMessage';
import { definition as manageTaskDef, handler as manageTaskHandler } from './definitions/manageTask';
import { definition as commandStatusDef, handler as commandStatusHandler } from './definitions/commandStatus';
import { definition as createTodoListDef, handler as createTodoListHandler } from './definitions/createTodoListTasks';
import { definition as updateTaskStatusDef, handler as updateTaskStatusHandler } from './definitions/updateTaskStatus';
import { definition as createFolderDef, handler as createFolderHandler } from './definitions/createFolder';
import { definition as deleteFolderDef, handler as deleteFolderHandler } from './definitions/deleteFolder';
import { definition as renameFolderDef, handler as renameFolderHandler } from './definitions/renameFolder';
import { definition as findTextDef, handler as findTextHandler } from './definitions/findText';
import { definition as searchDef, handler as searchHandler } from './definitions/search';
import { definition as executeCodeDef, handler as executeCodeHandler } from './definitions/executeCode';
import { definition as analyzeDependenciesDef, handler as analyzeDependenciesHandler } from './definitions/analyzeDependencies';
import { definition as formatCodeDef, handler as formatCodeHandler } from './definitions/formatCode';
import { definition as runTestsDef, handler as runTestsHandler } from './definitions/runTests';
import { definition as getGitBranchDef, handler as getGitBranchHandler } from './definitions/getGitBranch';
import { definition as createBranchDef, handler as createBranchHandler } from './definitions/createBranch';
import { definition as downloadFileDef, handler as downloadFileHandler } from './definitions/downloadFile';
import { definition as getFileInfoDef, handler as getFileInfoHandler } from './definitions/getFileInfo';
import { definition as compareFilesDef, handler as compareFilesHandler } from './definitions/compareFiles';
import { definition as findDuplicatesDef, handler as findDuplicatesHandler } from './definitions/findDuplicates';
import { definition as checkSyntaxDef, handler as checkSyntaxHandler } from './definitions/checkSyntax';
import { definition as compressFileDef, handler as compressFileHandler } from './definitions/compressFile';
import { definition as extractArchiveDef, handler as extractArchiveHandler } from './definitions/extractArchive';
import { definition as validateSchemaDef, handler as validateSchemaHandler } from './definitions/validateSchema';
import { definition as generateDocumentationDef, handler as generateDocumentationHandler } from './definitions/generateDocumentation';
import { definition as refactorCodeDef, handler as refactorCodeHandler } from './definitions/refactorCode';
import { definition as convertFormatDef, handler as convertFormatHandler } from './definitions/convertFormat';
import { definition as optimizeImageDef, handler as optimizeImageHandler } from './definitions/optimizeImage';
import { definition as mergeBranchDef, handler as mergeBranchHandler } from './definitions/mergeBranch';
import { definition as screenshotDef, handler as screenshotHandler } from './definitions/screenshot';
import { definition as listWindowsDef, handler as listWindowsHandler } from './definitions/listWindows';
import { definition as getClipboardDef, handler as getClipboardHandler } from './definitions/getClipboard';
import { definition as setClipboardDef, handler as setClipboardHandler } from './definitions/setClipboard';
import { definition as listProcessesDef, handler as listProcessesHandler } from './definitions/listProcesses';
import { definition as killProcessDef, handler as killProcessHandler } from './definitions/killProcess';
import { definition as readArtifactDef, handler as readArtifactHandler } from './definitions/readArtifact';

export * from './types';
export * from './registry';
export * from './executor';
export * from './formatter';
export * from './readOnly';
export * from './planModePolicy';

export function initializeTools() {
  registerTool(readFileDef, readFileHandler);
  registerTool(writeFileDef, writeFileHandler);
  registerTool(editFileDef, editFileHandler);
  registerTool(createFileDef, createFileHandler);
  registerTool(renameFileDef, renameFileHandler);
  registerTool(listDirectoryDef, listDirectoryHandler);
  registerTool(searchFilesDef, searchFilesHandler);
  registerTool(runCommandDef, runCommandHandler);
  registerTool(gitStatusDef, gitStatusHandler);
  registerTool(gitAddDef, gitAddHandler);
  registerTool(gitCommitDef, gitCommitHandler);
  registerTool(gitDiffDef, gitDiffHandler);
  registerTool(webSearchDef, webSearchHandler);
  registerTool(readUrlDef, readUrlHandler);
  registerTool(askUserDef, askUserHandler);
  registerTool(codeAnalysisDef, codeAnalysisHandler);
  registerTool(invokeSubagentDef, invokeSubagentHandler);
  registerTool(sendMessageDef, sendMessageHandler);
  registerTool(manageTaskDef, manageTaskHandler);
  registerTool(commandStatusDef, commandStatusHandler);
  registerTool(createTodoListDef, createTodoListHandler);
  registerTool(updateTaskStatusDef, updateTaskStatusHandler);
  registerTool(createFolderDef, createFolderHandler);
  registerTool(deleteFolderDef, deleteFolderHandler);
  registerTool(renameFolderDef, renameFolderHandler);
  registerTool(findTextDef, findTextHandler);
  registerTool(searchDef, searchHandler);
  registerTool(executeCodeDef, executeCodeHandler);
  registerTool(analyzeDependenciesDef, analyzeDependenciesHandler);
  registerTool(formatCodeDef, formatCodeHandler);
  registerTool(runTestsDef, runTestsHandler);
  registerTool(getGitBranchDef, getGitBranchHandler);
  registerTool(createBranchDef, createBranchHandler);
  registerTool(downloadFileDef, downloadFileHandler);
  registerTool(getFileInfoDef, getFileInfoHandler);
  registerTool(compareFilesDef, compareFilesHandler);
  registerTool(findDuplicatesDef, findDuplicatesHandler);
  registerTool(checkSyntaxDef, checkSyntaxHandler);
  registerTool(compressFileDef, compressFileHandler);
  registerTool(extractArchiveDef, extractArchiveHandler);
  registerTool(validateSchemaDef, validateSchemaHandler);
  registerTool(generateDocumentationDef, generateDocumentationHandler);
  registerTool(refactorCodeDef, refactorCodeHandler);
  registerTool(convertFormatDef, convertFormatHandler);
  registerTool(optimizeImageDef, optimizeImageHandler);
  registerTool(mergeBranchDef, mergeBranchHandler);
  registerTool(screenshotDef, screenshotHandler);
  registerTool(listWindowsDef, listWindowsHandler);
  registerTool(getClipboardDef, getClipboardHandler);
  registerTool(setClipboardDef, setClipboardHandler);
  registerTool(listProcessesDef, listProcessesHandler);
  registerTool(killProcessDef, killProcessHandler);
  registerTool(readArtifactDef, readArtifactHandler);
}

// Automatically register all tools when the module loads to survive HMR
initializeTools();
